using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Numerics;

/*
 Highly divisible triangular number
Problem 12 
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors? 
 */

namespace ProjectEulerProblem12_HighlyDivisibleTriangularNumber
{
    class Program
    {
        static void Main(string[] args)
        {
            int divisors = 0;
            int i = 0;
            int j = 0;
            int triangle = 0;
            while(divisors<502)
            {
                i++;
                triangle += i;
                divisors = 0;
                for (j=1;j<=triangle/2;j++) //division beyond half the number is useless up to division by itself
                {
                    if (triangle % j == 0)
                        divisors += 1;
                }
                divisors += 1;
                //Console.WriteLine(divisors);
                //Console.WriteLine(triangle);
            }
            Console.WriteLine(triangle);
            Console.WriteLine(divisors);
        }
    }
}
